name: angel_flutter
version: 1.0.0-alpha
description: Widgets and helpers for developing Flutter clients for Angel applications.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/flutter
environment:
  sdk: ">=1.19.0"
dependencies:
  angel_client: ">=1.1.0 <2.0.0"
  flutter:
    sdk: flutter
  meta: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  http_mock: ^1.0.0