name: angel_flutter
version: 1.0.0-alpha.1
description: Widgets and helpers for developing Flutter clients for Angel applications.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/flutter
environment:
  sdk: ">=2.0.0"
dependencies:
  angel_client: ^2.0.0
  angel_websocket: ^2.0.0
  async: ^2.0.0
  flutter:
    sdk: flutter
  meta: ^1.0.0
  shared_preferences: ^0.5.2
  uni_links: ^0.2.0
  url_launcher: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0