name: "example_common"
dependencies: 
  angel_framework: "^1.0.0"
  angel_model: "^1.0.0"
  angel_serialize: "^1.0.0-alpha"
dev_dependencies: 
  angel_serialize_generator: "^1.0.0-alpha"
  build_runner: "^0.5.0"
